export const pokemon = [
  {
    name: "Nidoran-f",
    type: "Poison",
    description: "A small Sharp Girl",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Nidorina",
    evolutionTwo: "Nidoqueen",
    pokemonId: 0,
    pokemonURL: "assets/img/Nidoran-f.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoran♀_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/Nidoran-fStats.png",
    evolves: "LV 16",
  },
  {
    name: "Nidorina",
    type: "Poison",
    description: "A Sharb Girl",
    prevolutionOne: "Nidoran-f",
    prevolutionTwo: "None",
    evolutionOne: "Nidoking",
    evolutionTwo: "None",
    pokemonId: 1,
    pokemonURL: "assets/img/Nidorina.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidorina_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/NidorinaStats.png",
    evolves: "Moon Stone",
  },
  {
    name: "Nidoqueen",
    type: "Poison",
    description: "A Big Sharp Girl",
    prevolutionOne: "Nidorina",
    prevolutionTwo: "Nidoran-f",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 2,
    pokemonURL: "assets/img/Nidoqueen.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoqueen_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/NidoqueenStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Nidoran",
    type: "Poison",
    description: "A small Sharp Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Nidorino",
    evolutionTwo: "Nidoking",
    pokemonId: 3,
    pokemonURL: "assets/img/Nidoran.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoran♂_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/NidoranStats.png",
    evolves: "LV 16",
  },
  {
    name: "Nidorino",
    type: "Poison",
    description: "A Sharb Boy",
    prevolutionOne: "Nidoran",
    prevolutionTwo: "None",
    evolutionOne: "Nidoking",
    evolutionTwo: "None",
    pokemonId: 4,
    pokemonURL: "assets/img/Nidorino.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidorino_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/NidorinoStats.png",
    evolves: "Moon Stone",
  },
  {
    name: "Nidoking",
    type: "Poison",
    description: "A Big Sharp Boy",
    prevolutionOne: "Nidorino",
    prevolutionTwo: "Nidoran",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 5,
    pokemonURL: "assets/img/Nidoking.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoking_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/NidokingStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Voltorb",
    type: "Electric",
    description: "A small bally Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Electrode",
    evolutionTwo: "None",
    pokemonId: 6,
    pokemonURL: "assets/img/Voltorb.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Voltorb_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/VoltorbStats.jpg",
    evolves: "LV 30",
  },
  {
    name: "Electrode",
    type: "Electric",
    description: "A big bally Boy",
    prevolutionOne: "Voltorb",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 7,
    pokemonURL: "assets/img/Electrode.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Electrode_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/ElectrodeStats.jpg",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Geodude",
    type: "Rock",
    description: "A small Rocky Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Graveler",
    evolutionTwo: "Golem",
    pokemonId: 8,
    pokemonURL: "assets/img/Geodude.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Geodude_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/GeodudeStats.png",
    evolves: "LV 25",
  },
  {
    name: "Graveler",
    type: "Rock",
    description: "A Rocky Boy",
    prevolutionOne: "Geodude",
    prevolutionTwo: "None",
    evolutionOne: "Golem",
    evolutionTwo: "None",
    pokemonId: 9,
    pokemonURL: "assets/img/Graveler.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Graveler_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/GravelerStats.jpg",
    evolves: "Traded",
  },
  {
    name: "Golem",
    type: "Rock",
    description: "A big Rocky Boy",
    prevolutionOne: "Graveler",
    prevolutionTwo: "Geodude",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 10,
    pokemonURL: "assets/img/Golem.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Golem_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/GolemStuff.jpg",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Magnemite",
    type: "Electric",
    description: "A Small Magnet Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Magneton",
    evolutionTwo: "Magnezone",
    pokemonId: 11,
    pokemonURL: "assets/img/Magnemite.png",
    generation: "First Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Magnemite_(Pok%C3%A9mon)",
   stats: "assets/PokemonStats/MagnemiteStats.png",
    evolves: "LV 30",
  },
  {
    name: "Magneton",
    type: "Electric",
    description: "A Magnet Boi",
    prevolutionOne: "Magnemite",
    prevolutionTwo: "None",
    evolutionOne: "Magnezone",
    evolutionTwo: "None",
    pokemonId: 12,
    pokemonURL: "assets/img/Magneton.png",
    generation: "First Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Magneton_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/MagnetonStats.png",
    evolves: "Magnet Cave",
  },
  {
    name: "Magnezone",
    type: "Electric",
    description: "A Big Magnet Boi",
    prevolutionOne: "Magneton",
    prevolutionTwo: "Magnemite",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 13,
    pokemonURL: "assets/img/Magnezone.png",
    generation: "First Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Magnezone_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/MagnezoneStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Wynaut",
    type: "Psychic",
    description: "A Small Punching Bag",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Wobuffet",
    evolutionTwo: "None",
    pokemonId: 14,
    pokemonURL: "assets/img/Wynaut.png",
    generation: "Second Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Wynaut_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/WynautStats.jpg",
    evolves: "LV 15",
  },
  {
    name: "Wobuffet",
    type: "Psychic",
    description: "A Punching Bag",
    prevolutionOne: "Wynaut",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 15,
    pokemonURL: "assets/img/Wobuffet.png",
    generation: "Second Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Wobuffet_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/WobuffetStats.jpg",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Yanma",
    type: "Bug",
    description: "A Dragonfly Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Yanmega",
    evolutionTwo: "None",
    pokemonId: 16,
    pokemonURL: "assets/img/Yanma.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Yanma_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/YanmaStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Yanmega",
    type: "Bug",
    description: "A Big Dragonfly Boi",
    prevolutionOne: "Yanma",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 17,
    pokemonURL: "assets/img/Yanmega.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Yanmega_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/YanmegaStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Cranidos",
    type: "Rock",
    description: "A Small Rammy Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Rampardos",
    evolutionTwo: "None",
    pokemonId: 18,
    pokemonURL: "assets/img/Cranidos.png",
    generation: "Fourth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Cranidos_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/CranidosStats.png",
    evolves: "LV 30",
  },
  {
    name: "Rampardos",
    type: "Rock",
    description: "A big Rammy Boy",
    prevolutionOne: "Crainidos",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 19,
    pokemonURL: "assets/img/Rampardos.png",
    generation: "Fourth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Rampardos_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/RampardosStats.jpg",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Tynamo",
    type: "Electric",
    description: "A Tiny Fishy Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Elektrik",
    evolutionTwo: "Electross",
    pokemonId: 20,
    pokemonURL: "assets/img/Tynamo.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Tynamo_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/TynamoStats.jpg",
    evolves: "LV 39",
  },
  {
    name: "Elektrik",
    type: "Electric",
    description: "A Fishy Boy",
    prevolutionOne: "Tynamo",
    prevolutionTwo: "None",
    evolutionOne: "Electross",
    evolutionTwo: "None",
    pokemonId: 21,
    pokemonURL: "assets/img/Elektrik.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/eelektrik_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/ElektrikStats.jpg",
    evolves: "Thunder Stone",
  },
  {
    name: "Elektross",
    type: "Electric",
    description: "A big Fishy Boy",
    prevolutionOne: "Elektrik",
    prevolutionTwo: "Tynamo",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 22,
    pokemonURL: "assets/img/Elektross.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/eelektross_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/ElektrossStats.jpg",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Roggenrola",
    type: "Rock",
    description: "A Little rock",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Boldore",
    evolutionTwo: "Gigalith",
    pokemonId: 23,
    pokemonURL: "assets/img/Roggenrola.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/Roggenrola_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/RoggenrolaStats.png",
    evolves: "LV 25",
  },
  {
    name: "Boldore",
    type: "Rock",
    description: "A Rock",
    prevolutionOne: "Roggenrola",
    prevolutionTwo: "None",
    evolutionOne: "Gigalith",
    evolutionTwo: "None",
    pokemonId: 24,
    pokemonURL: "assets/img/Boldore.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Boldore_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/BoldoreStats.png",
    evolves: "Traded",
  },
  {
    name: "Gigalith",
    type: "Rock",
    description: "A Big Rock",
    prevolutionOne: "Boldore",
    prevolutionTwo: "Roggenrola",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 25,
    pokemonURL: "assets/img/Gigalith.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Gigalith_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/GigalithStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Ferroseed",
    type: "Steel",
    description: "A Spiky Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Ferrothorn",
    evolutionTwo: "None",
    pokemonId: 26,
    pokemonURL: "assets/img/Ferroseed.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Ferroseed_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/FerroseedStats.png",
    evolves: "LV 40",
  },
  {
    name: "Ferrothorn",
    type: "Steel",
    description: "A Spiky Boy",
    prevolutionOne: "Ferroseed",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 27,
    pokemonURL: "assets/img/Ferrothorn.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/Ferrothorn_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/FerrothornStats.png",
    evolves: "Doesn't Evolve",
  },  
  {
    name: "Sawk",
    type: "Fighting",
    description: "A Kungfu Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 28,
    pokemonURL: "assets/img/Sawk.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Sawk_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/SawkStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Throh",
    type: "Fighting",
    description: "A Judo Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 29,
    pokemonURL: "assets/img/Throh.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Throh_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/ThrohStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Sandile",
    type: "Ground",
    description: "A Smal Croc Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Krokorok",
    evolutionTwo: "Krookodile",
    pokemonId: 30,
    pokemonURL: "assets/img/Sandile.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Sandile_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/SandileStats.png",
    evolves: "LV 29",
  },
  {
    name: "Krokorok",
    type: "Ground",
    description: "A Croc Boi",
    prevolutionOne: "Sandile",
    prevolutionTwo: "None",
    evolutionOne: "Krookodile",
    evolutionTwo: "None",
    pokemonId: 31,
    pokemonURL: "assets/img/Krokorok.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Krokorok_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/KrokorokStats.png",
    evolves: "LV 40",
  },
  {
    name: "Krookodile",
    type: "Ground",
    description: "A Big Croc Boi",
    prevolutionOne: "Krokorok",
    prevolutionTwo: "None",
    evolutionOne: "Sandile",
    evolutionTwo: "None",
    pokemonId: 32,
    pokemonURL: "assets/img/Krookodile.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Krookodile_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/KrookodileStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Pawniard",
    type: "Dark",
    description: "A Small Pointy Boi",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Bisharp",
    evolutionTwo: "None",
    pokemonId: 33,
    pokemonURL: "assets/img/Pawniard.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Pawniard_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/PawniardStats.png",
    evolves: "LV 52",
  },
  {
    name: "Bisharp",
    type: "Dark",
    description: "A Big Pointy Boi",
    prevolutionOne: "Pawniard",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 34,
    pokemonURL: "assets/img/Bisharp.png",
    generation: "Fifth Generation",
    BulbURL:
    "https://bulbapedia.bulbagarden.net/wiki/Bisharp_(Pok%C3%A9mon)",
    stats: "assets/PokemonStats/BisharpStats.png",
    evolves: "Doesn't Evolve",
  },
  {
    name: "Missingno",
    type: "Mystery",
    description: "A dead Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 35,
    pokemonURL: "assets/img/Missingno.png",
    generation: "First Generation",
    evolves: "Doesn't Evolve",
  },
];

/*
  Copyright Google LLC. All Rights Reserved.
  Use of this source code is governed by an MIT-style license that
  can be found in the LICENSE file at http://angular.io/license
  */
