export const shinypokemon = [
  {
    name: "Nidoran-f",
    type: "Poison",
    description: "A small Sharp Girl",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Nidorina",
    evolutionTwo: "Nidoqueen",
    pokemonId: 0,
    pokemonURL: "assets/img/ShinyNidoran-f.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoran♀_(Pok%C3%A9mon)",
    stats: "assets/img/Nidoran-fStats.png"
  },
  {
    name: "Nidorina",
    type: "Poison",
    description: "A Sharb Girl",
    prevolutionOne: "Nidoran-f",
    prevolutionTwo: "None",
    evolutionOne: "Nidoking",
    evolutionTwo: "None",
    pokemonId: 1,
    pokemonURL: "assets/img/ShinyNidorina.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidorina_(Pok%C3%A9mon)",
    stats: "assets/img/NidorinaStats.png"
  },
  {
    name: "Nidoqueen",
    type: "Poison",
    description: "A Big Sharp Girl",
    prevolutionOne: "Nidorina",
    prevolutionTwo: "Nidoran-f",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 2,
    pokemonURL: "assets/img/ShinyNidoqueen.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoqueen_(Pok%C3%A9mon)",
    stats: "assets/img/NidoqueenStats.png"
  },
  {
    name: "Nidoran",
    type: "Poison",
    description: "A small Sharp Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Nidorino",
    evolutionTwo: "Nidoking",
    pokemonId: 3,
    pokemonURL: "assets/img/ShinyNidoran.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoran♂_(Pok%C3%A9mon)",
    stats: "assets/img/NidoranStats.png"
  },
  {
    name: "Nidorino",
    type: "Poison",
    description: "A Sharb Boy",
    prevolutionOne: "Nidoran",
    prevolutionTwo: "None",
    evolutionOne: "Nidoking",
    evolutionTwo: "None",
    pokemonId: 4,
    pokemonURL: "assets/img/ShinyNidorino.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidorino_(Pok%C3%A9mon)",
    stats: "assets/img/NidorinoStats.png"
  },
  {
    name: "Nidoking",
    type: "Poison",
    description: "A Big Sharp Boy",
    prevolutionOne: "Nidorino",
    prevolutionTwo: "Nidoran",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 5,
    pokemonURL: "assets/img/ShinyNidoking.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Nidoking_(Pok%C3%A9mon)",
    stats: "assets/img/NidokingStats.png"
  },
  {
    name: "Voltorb",
    type: "Electric",
    description: "A Small Bally Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Electrode",
    evolutionTwo: "None",
    pokemonId: 6,
    pokemonURL: "assets/img/ShinyVoltorb.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Voltorb_(Pok%C3%A9mon)",
    stats: "assets/img/VoltorbStats.jpg"
  },
  {
    name: "Electrode",
    type: "Electric",
    description: "A Big Bally Boy",
    prevolutionOne: "Voltorb",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 7,
    pokemonURL: "assets/img/ShinyElectrode.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Electrode_(Pok%C3%A9mon)",
    stats: "assets/img/ElectrodeStats.jpg"
  },
  {
    name: "Geodude",
    type: "Rock",
    description: "A Small Rocky Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Graveler",
    evolutionTwo: "Golem",
    pokemonId: 8,
    pokemonURL: "assets/img/ShinyGeodude.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Geodude_(Pok%C3%A9mon)",
    stats: "assets/img/GeodudeStats.png"
  },
  {
    name: "Graveler",
    type: "Rock",
    description: "A Rocky Boy",
    prevolutionOne: "Geodude",
    prevolutionTwo: "None",
    evolutionOne: "Golem",
    evolutionTwo: "None",
    pokemonId: 9,
    pokemonURL: "assets/img/ShinyGraveler.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Graveler_(Pok%C3%A9mon)",
    stats: "assets/img/GravelerStats.jpg"
  },
  {
    name: "Golem",
    type: "Rock",
    description: "A Big Rocky Boy",
    prevolutionOne: "Graveler",
    prevolutionTwo: "Geodude",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 10,
    pokemonURL: "assets/img/ShinyGolem.jpg",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Golem_(Pok%C3%A9mon)",
    stats: "assets/img/GolemStuff.jpg"
  },
  {
    name: "Wynaut",
    type: "Psychic",
    description: "A Small Punching Bag",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Wobuffet",
    evolutionTwo: "None",
    pokemonId: 11,
    pokemonURL: "assets/img/ShinyWynaut.png",
    generation: "Second Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Wynaut_(Pok%C3%A9mon)",
    stats: "assets/img/WynautStats.jpg",
  },
  {
    name: "Wobuffet",
    type: "Psychic",
    description: "A Punching Bag",
    prevolutionOne: "Wynaut",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 12,
    pokemonURL: "assets/img/ShinyWobuffet.png",
    generation: "Second Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Wobuffet_(Pok%C3%A9mon)",
    stats: "assets/img/WobuffetStats.jpg",
  },
  {
    name: "Cranidos",
    type: "Rock",
    description: "A Small Rammy Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Rampardos",
    evolutionTwo: "None",
    pokemonId: 13,
    pokemonURL: "assets/img/ShinyCranidos.png",
    generation: "Fourth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Cranidos_(Pok%C3%A9mon)",
    stats: "assets/img/CranidosStats.png"
  },
  {
    name: "Rampardos",
    type: "Rock",
    description: "A Big Rammy Boy",
    prevolutionOne: "Crainidos",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 14,
    pokemonURL: "assets/img/ShinyRampardos.png",
    generation: "Fourth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Rampardos_(Pok%C3%A9mon)",
    stats: "assets/img/RampardosStats.jpg"
  },
  {
    name: "Tynamo",
    type: "Electric",
    description: "A Tiny Fishy Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Elektrik",
    evolutionTwo: "Electross",
    pokemonId: 15,
    pokemonURL: "assets/img/ShinyTynamo.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Tynamo_(Pok%C3%A9mon)",
    stats: "assets/img/TynamoStats.jpg"
  },
  {
    name: "Elektrik",
    type: "Electric",
    description: "A Fishy Boy",
    prevolutionOne: "Tynamo",
    prevolutionTwo: "None",
    evolutionOne: "Electross",
    evolutionTwo: "None",
    pokemonId: 16,
    pokemonURL: "assets/img/ShinyElektrik.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/eelektrik_(Pok%C3%A9mon)",
    stats: "assets/img/ElektrikStats.jpg"
  },
  {
    name: "Elektross",
    type: "Electric",
    description: "A Big Fishy Boy",
    prevolutionOne: "Elektrik",
    prevolutionTwo: "Tynamo",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 17,
    pokemonURL: "assets/img/ShinyElektross.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/eelektross_(Pok%C3%A9mon)",
    stats: "assets/img/ElektrossStats.jpg"
  },
  {
    name: "Roggenrola",
    type: "Rock",
    description: "A Little rock",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Boldore",
    evolutionTwo: "Gigalith",
    pokemonId: 18,
    pokemonURL: "assets/img/ShinyRoggenrola.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/Roggenrola_(Pok%C3%A9mon)",
    stats: "assets/img/RoggenrolaStats.png"
  },
  {
    name: "Boldore",
    type: "Rock",
    description: "A Rock",
    prevolutionOne: "Roggenrola",
    prevolutionTwo: "None",
    evolutionOne: "Gigalith",
    evolutionTwo: "None",
    pokemonId: 19,
    pokemonURL: "assets/img/ShinyBoldore.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Boldore_(Pok%C3%A9mon)",
    stats: "assets/img/BoldoreStats.png"
  },
  {
    name: "Gigalith",
    type: "Rock",
    description: "A Big Rock",
    prevolutionOne: "Boldore",
    prevolutionTwo: "Roggenrola",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 20,
    pokemonURL: "assets/img/ShinyGigalith.png",
    generation: "Second Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Gigalith_(Pok%C3%A9mon)",
    stats: "assets/img/GigalithStats.png"
  },
  {
    name: "Ferroseed",
    type: "Steel",
    description: "A Spiky Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "Ferrothorn",
    evolutionTwo: "None",
    pokemonId: 21,
    pokemonURL: "assets/img/ShinyFerroseed.png",
    generation: "Fifth Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Ferroseed_(Pok%C3%A9mon)",
    stats: "assets/img/FerroseedStats.png"
  },
  {
    name: "Ferrothorn",
    type: "Steel",
    description: "A Spiky Boy",
    prevolutionOne: "Ferroseed",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 22,
    pokemonURL: "assets/img/ShinyFerrothorn.png",
    generation: "Fifth Generation",
    BulbURL:
      "https://bulbapedia.bulbagarden.net/wiki/Ferrothorn_(Pok%C3%A9mon)",
    stats: "assets/img/FerrothornStats.png"
  },
  {
    name: "Missingno",
    type: "Mystery",
    description: "A Dead Boy",
    prevolutionOne: "None",
    prevolutionTwo: "None",
    evolutionOne: "None",
    evolutionTwo: "None",
    pokemonId: 23,
    pokemonURL: "assets/img/Missingno.png",
    generation: "First Generation",
    BulbURL: "https://bulbapedia.bulbagarden.net/wiki/Missingno._(Pok%C3%A9mon)"
  },
];

/*
    Copyright Google LLC. All Rights Reserved.
    Use of this source code is governed by an MIT-style license that
    can be found in the LICENSE file at http://angular.io/license
    */
